### ISSUE TITLE
Human-readable messages?

### ISSUE THREAD

**Issue by MurphyMc** [MurphyMc/depz#3]
Right now, you have to understand some of the git messages (i.e., for --outdated).  Human readable ones might be nice.  From @AbePralle:

> WARNING: it appears the repository XYZ is in a conflicted state with its origin.  If the repo has local changes, manually merge or otherwise synchronize it. If it doesn't have local changes, delete it and run 'depz --init' to restore it.

**Comment by MurphyMc** [comment]
@AbePralle is this resolved now?

**Comment by AbePralle** [comment]
Yep, resolved in [bfd10d9](https://github.com/MurphyMc/depz/commit/bfd10d9d8a2d59e459520d3595ffad0a4e630ca3).
